name: Continuous Integration Back-end
on: [push]
jobs:
  laravel-ContTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copiar ENV o revisar si existe
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Intalar npm
      working-directory: ./touristApp/
      run: npm install
    - name: Compilar con npm
      working-directory: ./touristApp/
      run: npm run dev
    - name: Empaquetar back-end
      run: zip -r dev_eritas.zip ./touristApp/resources/views/
    - name: Comprobar que el zip esta generado
      run: unzip -l dev_eritas.zip | less
      

