name: Continuous Integration Compilation
on: [push]
jobs:
  laravel-ContTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copiar ENV o revisar si existe
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Compilar con npm
      working-directory: ./touristApp/
      run: npm run dev
